[package]
name = "scenescope-desktop"
description = "Native desktop entry point for SceneScope"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = "0.33.3"
pollster = "1.0.1"
scenescope-core = { version = "0.1.0", path = "../../crates/scenescope-core" }
scenescope-gltf = { version = "0.1.0", path = "../../crates/scenescope-gltf" }
wgpu = "30.0.0"
winit = "0.30.13"
